### ISSUE TITLE
Try to build docker image with Bazel

### ISSUE THREAD

**Issue by Yohuan** [Yohuan/play_bazel#7]
# Overbiew

Build docker image with Bazel.
- To run a binary also built by Bazel

# Todo

- [x] Play [examples-bazel-containers-hasher](https://github.com/speak2jc/examples-bazel-containers-hasher)

  - Encounter the following error

```bash
docker run -it --rm speak2jc/cmd/api:image /bin/bash
standard_init_linux.go:228: exec user process caused: no such file or directory
```

- [x] Try [py3_image](https://github.com/bazelbuild/rules_docker#py3_image)
- [ ] Try [container_push](https://github.com/bazelbuild/rules_docker/blob/master/docs/container.md#container_push)
- [ ] Use `python:3.8-alpine` as py3 base image

# Reference

- [rules_docker](https://github.com/bazelbuild/rules_docker)
- [container api doc](https://github.com/bazelbuild/rules_docker/blob/master/docs/container.md)

# Articles

- [Create Container images with Bazel](https://dev.to/schoren/create-container-images-with-bazel-47am)
